### ISSUE TITLE
zoie support

### ISSUE THREAD

**Issue by ghost** [tjake/Solandra#1]
Hi,
"Zoie is a real-time search and indexing system built on Apache Lucene." http://sna-projects.com/zoie/

Zoie is much more efficient in indexing, so it's more suitable in this kind of operations. LinkedIn is using it (and developed). It'll be perfect if you support zoie or replace lucene with it.

Best Regards,

**Comment by tjake** [comment]
Not sure how this relates to Lucandra?  In many ways Lucandra provides the same benefits as zoie.  distributed search, real-time, etc.
