### ISSUE TITLE
Build seems to be broken

### ISSUE THREAD

**Issue by mark-watson** [tjake/Solandra#100]
[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]  io problem while parsing ivy file: https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom: Resetting to invalid mark
[ivy:retrieve]  io problem while parsing ivy file: http://repo1.maven.org/maven2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom: Resetting to invalid mark
[ivy:retrieve]      module not found: org.apache.velocity#velocity;1.6.4
[ivy:retrieve]  ==== java.net2: tried
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]    -- artifact org.apache.velocity#velocity;1.6.4!velocity.jar:
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.jar
[ivy:retrieve]  ==== cloudera: tried
[ivy:retrieve]    https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]  ==== ibiblio: tried
[ivy:retrieve]    http://repo1.maven.org/maven2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]  io problem while parsing ivy file: https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom: Resetting to invalid mark
[ivy:retrieve]  io problem while parsing ivy file: http://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom: Resetting to invalid mark
[ivy:retrieve]      module not found: org.apache.velocity#velocity-tools;2.0
[ivy:retrieve]  ==== java.net2: tried
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]    -- artifact org.apache.velocity#velocity-tools;2.0!velocity-tools.jar:
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ivy:retrieve]  ==== cloudera: tried
[ivy:retrieve]    https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]  ==== ibiblio: tried
[ivy:retrieve]    http://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]      :: org.apache.velocity#velocity;1.6.4: not found
[ivy:retrieve]      :: org.apache.velocity#velocity-tools;2.0: not found
[ivy:retrieve]      :: javax.servlet#servlet-api;2.5: configuration not found in javax.servlet#servlet-api;2.5: 'compile'. It was required from org.apache.thrift#libthrift;0.6.1 compile
[ivy:retrieve]      ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by tjake** [comment]
Hmm, I just did a fresh checkout and wiped out all my ivy/maven caches and was able to find all the dependencies... can you try again? perhaps it was a intermittent error? or are you behind a firewall?

**Comment by tjake** [comment]
not able to reproduce

**Comment by billau** [comment]
I just downloaded the tar ball and am having the same problem.  I am behind a firewall.

[ivy:retrieve] :: problems summary ::
[ivy:retrieve] :::: WARNINGS
[ivy:retrieve]  io problem while parsing ivy file: https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom: Resetting to invalid mark
[ivy:retrieve]  io problem while parsing ivy file: http://repo1.maven.org/maven2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom: Resetting to invalid mark
[ivy:retrieve]          module not found: org.apache.velocity#velocity;1.6.4
[ivy:retrieve]  ==== java.net2: tried
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]    -- artifact org.apache.velocity#velocity;1.6.4!velocity.jar:
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.jar
[ivy:retrieve]  ==== cloudera: tried
[ivy:retrieve]    https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]  ==== ibiblio: tried
[ivy:retrieve]    http://repo1.maven.org/maven2/org/apache/velocity/velocity/1.6.4/velocity-1.6.4.pom
[ivy:retrieve]  io problem while parsing ivy file: https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom: Resetting to invalid mark
[ivy:retrieve]  io problem while parsing ivy file: http://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom: Resetting to invalid mark
[ivy:retrieve]          module not found: org.apache.velocity#velocity-tools;2.0
[ivy:retrieve]  ==== java.net2: tried
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]    -- artifact org.apache.velocity#velocity-tools;2.0!velocity-tools.jar:
[ivy:retrieve]    http://download.java.net/maven/2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar
[ivy:retrieve]  ==== cloudera: tried
[ivy:retrieve]    https://repository.cloudera.com/content/groups/cdh-build/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]  ==== ibiblio: tried
[ivy:retrieve]    http://repo1.maven.org/maven2/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.pom
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          ::          UNRESOLVED DEPENDENCIES         ::
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]          :: org.apache.velocity#velocity;1.6.4: not found
[ivy:retrieve]          :: org.apache.velocity#velocity-tools;2.0: not found
[ivy:retrieve]          ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:retrieve]
