### ISSUE TITLE
Dropped cores?

### ISSUE THREAD

**Issue by davidstrauss** [tjake/Solandra#106]
After upgrading from Solandra for Solr 3.1 + Cassandra 0.7 to Solandra for Solr 3.2 + Cassandra 0.8, existing Solr cores have been rendered invalid (java.io.IOException: invalid core). The way I upgraded is by doing a fresh build (ant clean && ant), updating cassandra.yaml to point to my existing Cassandra persistence directory, and starting Solandra.

I'll keep investigating, but I'm not sure if the answer is obvious to people closer to the Solandra code.

**Comment by davidstrauss** [comment]
I've checked on the cassandra.yaml and CFs for the "L" keyspace, and I can't see any changes that would clearly break things.

**Comment by tjake** [comment]
Hi David. 

There was a change recently that allowed you to post ant solr resource to solandra not just schema.xml so this may hbe broken it. in general the solandra Datamodel has not yet stabilized. It's close but I'm pretty sure you will need to re-index. 
I haven't changed anything related to schemas but I have changed the term data format recently.

**Comment by tjake** [comment]
Sorry for the garbled message. Sending from my phone.

**Comment by davidstrauss** [comment]
Do you have any idea when the data model in Cassandra will stabilize or support upgrades from version-to-version? Or should we make plans to fully re-provision cores and reindex frequently?

**Comment by tjake** [comment]
I think it's close, next month or so. just clearing out the last of the facet bugs and I think we can release.
