### ISSUE TITLE
Issue with CassandraUtils.

### ISSUE THREAD

**Issue by mevivs** [tjake/Solandra#107]
Currently i am facing 1 issue with Solandra. I have my cassandra server running standalone on 9160. I have a thrift client connected to server for inserting my schema. Now for indexing i have intialized Solandra with CassandraUtils.startUpClient() and CassandraUtils.CreateCassandraSchema(). But somehow system tables like ('L', 'TI' etc.) are not getting created.

But interestingly this works fine when i start Cassandra Server in embedded mode using EmbeddedCassandraService.

**Comment by tjake** [comment]
Sorry, I'm confused...  Why are you not using SolandraServer?

**Comment by mevivs** [comment]
Reason for this is i want to start this implicitly within my app. 
Thanks, i am able to resolve this issue. But just wanted to ask, is there any specific reason for using CassandraServer cs = new CassandraServer() in CassandraUtils.java?

Should it be flxible enough to configure a client via external app?

**Comment by tjake** [comment]
solandra has a client mode "-c" flag that lets you run it against a existing cassandra cluster.  internally this calls the CassandraUtils startupClient() method.  Is this what you need?

**Comment by mevivs** [comment]
Thanks... But will that load my updated db, as same is done by CassandraDaemon.activate() ?
I mean loading metadata, DatabaseDescription defs etc.
