### ISSUE TITLE
Fails to run on Windows 7

### ISSUE THREAD

**Issue by chaostheory** [tjake/Solandra#117]
### Details:

I don't have the CASSANDRA_HOME or CASSANDRA_MAIN set.
### Result:

Running the batch file errors out with "Starting Cassandra server. The input line is too long."

**Comment by xytxytxyt** [comment]
Seems to work with the line 

for %%i in ("%CASSANDRA_HOME%\lib*.jar") do call :append "%%i"

replaced with 

set CLASSPATH=%CLASSPATH%;"%CASSANDRA_HOME%\lib*"

**Comment by smecsia** [comment]
That didn't work for me. So I've patched solandra.bat using the lines below.

:append
set "baseFilePath=%1"
call set "baseFilePath=%%baseFilePath:%CASSANDRA_HOME%=..%%"
set CLASSPATH=%CLASSPATH%;%baseFilePath%
goto :eof
