### ISSUE TITLE
Simple/Noob Question, I need to use IndexSearcher...

### ISSUE THREAD

**Issue by VanitySoft** [tjake/Solandra#133]
I've been using Lucandra(pre-0.7 or Cassandra), but  cassandra  had a bug that is resolved in the latest cassandra release, so I now need to use "Solandra"....so I am in the process of updating my code....

How can create an IndexSearcher programmatically using Solandra/Lucandra? Basically accessing lucene API directory...

Also,I am aware it is ideal to use the HTTP connection....but i have alot custom code that was performed accessing IndexSearcher directly.

**Comment by tjake** [comment]
I don't think this is possible you must use SolrJ
