### ISSUE TITLE
updateDocument call without deleting document

### ISSUE THREAD

**Issue by ceocoder** [tjake/Solandra#15]
Currently updateDocument works like this,

deleteDocument(doc);
addDocument(doc);

I was trying to see if update can be make to work like this,

updateDocument(doc, analyzer) {
foreach(field in doc)
if(field exists)
{
  delete its columns from TermVector CF
  add newly tokenized terms under same docId
}
else
{
  add newly tokenized terms under same docId
}

changing update to this, will save a lot on performance, 
- no more parsing entire document object for updating one field
- changes to cassandra will be a lot smaller

thanks,

}

**Comment by tjake** [comment]
This was inherited from lucene. see http://wiki.apache.org/lucene-java/LuceneFAQ#How_do_I_update_a_document_or_a_set_of_documents_that_are_already_indexed.3F

While this may be doable, I think it's going to end up having a lot of edge conditions and complexity.  But feel free to submit a patch :)

**Comment by ceocoder** [comment]
you are on the money with complexity, this is what I tried,

Deleting columns from TermVector CF but only for the field that needs to be updated, 

public String deleteDocuments(Term term) throws CorruptIndexException, IOException {
        String docId = "";
        try {

```
        ColumnParent cp = new ColumnParent(CassandraUtils.termVecColumnFamily);
        String key = indexName + CassandraUtils.delimeter + CassandraUtils.createColumnName(term);
        logger.debug("deleteDocuments term " + key);
        List<ColumnOrSuperColumn> docs = client.get_slice(CassandraUtils.keySpace, CassandraUtils.hashKey(key), cp, new SlicePredicate()
            .setSlice_range(new SliceRange(new byte[] {}, new byte[] {}, true, Integer.MAX_VALUE)), ConsistencyLevel.ONE);

        // delete by documentId
        for (ColumnOrSuperColumn docInfo : docs) {
            //get docId from doc being deleted  
            docId = new String(docInfo.column.name);
            logger.debug("in docInfo loop " + docId);
            deleteLucandraDocument(docInfo.column.name, term);
        }

    } catch (InvalidRequestException e) {
        throw new RuntimeException(e);
    } catch (UnavailableException e) {
        throw new RuntimeException(e);
    } catch (TException e) {
        throw new RuntimeException(e);
    } catch (TimedOutException e) {
        throw new RuntimeException(e);
    } catch (NotFoundException e) {
        throw new RuntimeException(e);
    } catch (ClassNotFoundException e) {
        throw new RuntimeException(e);
    }

    return docId;
```

}

private void deleteLucandraDocument(byte[] docId, Term term) throws InvalidRequestException, NotFoundException, UnavailableException, TimedOutException, TException,
            IOException, ClassNotFoundException {

```
    String key = indexName + CassandraUtils.delimeter + new String(docId);
    String fieldToUpdate = indexName + CassandraUtils.delimeter + term.field() + CassandraUtils.delimeter;

    ColumnOrSuperColumn column = client.get(CassandraUtils.keySpace, CassandraUtils.hashKey(key), CassandraUtils.metaColumnPath, ConsistencyLevel.ONE);

    List<String> terms = (List<String>) CassandraUtils.fromBytes(column.column.value);

    for (String termStr : terms) {

        key = indexName + CassandraUtils.delimeter + termStr;

        if (key.contains(fieldToUpdate)) {
            logger.debug("found a termVec match to remove " + key);
            CassandraUtils.addToMutationMap(mutationMap, CassandraUtils.termVecColumnFamily, docId, CassandraUtils.hashKey(key), null);
        } else {
            logger.debug("ignorig term vec with key  " + key);
        }
    }


    logger.debug(mutationMap);

    if (autoCommit)
        CassandraUtils.robustBatchInsert(client, mutationMap);

    //got rid of the self delete part
```

}

private void addDocumentWithDocId(Document doc, Analyzer analyzer, String docId) {
    using supplied docId instead of randomly generated
}

public void updateDocument(Term updateTerm, Document doc, Analyzer analyzer) {
    String docId = deleteDocuments(updateTerm);
    log.debug(docId)
    addDocumentWithDocId(doc, analyzer, docId);
}

am I on the right track, comments?

**Comment by tjake** [comment]
What if you really want to delete a field from a previous document? this only adds or replaces?

**Comment by ceocoder** [comment]
haven't thought it thru but I  guess you call updatedocumer with empty document object,
