### ISSUE TITLE
Lucandra slows down when the value of a term is often the same

### ISSUE THREAD

**Issue by mircouleur** [tjake/Solandra#16]
Hello tjake,

When the value of a term often occurs in a database Lucandra slows down. I' ve got a database with two categories (it's a Term) and many millions of others Terms. If I want to filter over one of the two categories Lucandra fetch half the database because of the Cassandra "sliceRange". 
Any idea to resolve this issue?
Thanx.

**Comment by tjake** [comment]
Yes this is a known issue. I'm considering writing a custom queryfilter class to deal with this situation. Can you filter it in your app layer for now?

**Comment by mircouleur** [comment]
It's difficult to filter in our app beacause we can't know witch Term will be inpacted by this issue. What is the idea of your custom queryfilter class? Maybe we could help you?
thanx

**Comment by tjake** [comment]
If the filter class knew which documents were fetched for all other search results then the query filter could simply filter those specific documents. 

Another short term idea for you: Try creating an index per category, so you can query from one or the other. rather than filtering from one.

**Comment by mircouleur** [comment]
Hi Jake,

I've made a queryfilter for this issue. How could I submit it?

**Comment by tjake** [comment]
Cool! If you know git then you can fork this project and patch it then I can merge it in. Otherwise you can email me the patch jakers at gmail. Thanks!

**Comment by mircouleur** [comment]
hello Jake,

It's in your mailbox. Did you receive it?

**Comment by tjake** [comment]
No. I didn't. Did you send it to jakers at gmail dot com?

**Comment by mircouleur** [comment]
Yes I did it sunday... the mail is from herve.dominguez at gmail dot com

**Comment by mircouleur** [comment]
Hi Jake,

Did you receive it, I made a reply on your message...

**Comment by tjake** [comment]
Yeah thanks. I'll look at this further tonight but what I saw looked great!
You should pick up git so you can contribute more easily :) look at the github tutorials

**Comment by tjake** [comment]
Checked in! thanks a ton, just what I was planning :)
