### ISSUE TITLE
TermQuery Search leads to exception "termFrequency is missing from supercolumn"

### ISSUE THREAD

**Issue by rob7hunter** [tjake/Solandra#18]
I'm trying to insert a url and then search for it again using a TermQuery search. The code below, which I run right inside the BookmarksDemo, results in a "termFrequency is missing from supercolumn" exception in the TopDocs line.

```
    Document doc = new Document();
    doc.add(new Field("url", "http://www.google.com",
                      Field.Store.YES, Field.Index.NOT_ANALYZED));
    indexWriter.addDocument(doc, analyzer);
    TermQuery tq = new TermQuery(new Term("url", "http://www.google.com"));
    TopDocs topDocs = indexSearcher.search(tq, 10);
```

Note that if you change the url you are _searching_ for to, say, "http://www.amazon.com", the code finds 0 results without an exception (this is correct since amazon isn't indexed).

**Comment by tjake** [comment]
Is your Cassandra config upto date? I stared using supercolumns a few weeks ago so you'll need to recreate your indexes.

**Comment by rob7hunter** [comment]
Yeah, the ColumnFamily tags now look like this, as per what's checked in to the lucandra github. This exception is from a fresh build of today's code and a wiped cassandra db, so I expect it's reproducible with the code I provided.

```
<ColumnFamily CompareWith="BytesType" Name="Documents"   KeysCached="10%" />
<ColumnFamily ColumnType="Super" CompareWith="BytesType" CompareSubcolumnsWith="BytesType"
            Name="TermInfo" KeysCached="10%" />
```

**Comment by tjake** [comment]
Fixed. thx for the report

**Comment by rob7hunter** [comment]
Works on my end now. Thanks!
