### ISSUE TITLE
sort working so slow?

### ISSUE THREAD

**Issue by eurospy** [tjake/Solandra#19]
I have a data set which includes about 1M documets,

A search query with 3k results even with filtering works fine; however if I try to add a sort field like using the constructs
...
Sort sort = new Sort(new SortField("date", SortField.STRING));
...
TopDocs docs = searcher.search(q, filter, 10, sort);

it either hangs up for a while and does nothing or I get a timeout exception.

Isn't the sort working properly or am I missing something in the usage of sort?

**Comment by eurospy** [comment]
if it's somehow possible to make the default sort order to be the date by some trick (like tampering with the docId or so) I think the main problem might be solved.

**Comment by tjake** [comment]
Yes that's the idea.  I'm working on this.  Its also possible to do something like the query filter but for sorting.

**Comment by eurospy** [comment]
So, currently what is the default sort order? can you scheme out it?

**Comment by eurospy** [comment]
it seems like it's the based on the first field in such a query like "date:[2010.01 TO 2010.02] AND id:[100 TO 200]"

**Comment by tjake** [comment]
This is a fundemental problem with lucandra, the newer solandra should handle this problem better.
