### ISSUE TITLE
[RuntimeException: termFrequency is missing from supercolumn] on wildcard search in Lucandra

### ISSUE THREAD

**Issue by mir-ali** [tjake/Solandra#21]
Hi Jake,

I am using Lucandra for indexing. I am adding a field to a document as follows:

<code>document.add(new Field("fieldName",  "val!IN_20002001!IN_20002002!OUT_20002003!OUT_20002004", Store.NO,  Index.NOT_ANALYZED));</code>

Along with the field above, I have added a bunch of other fields to the document and then indexed it using the indexWriter as follows:

```
indexWriter.addDocument(document, analyzer);
```

So when I do a query such as following one:
    "fieldName:val_"
I am getting the exception mentioned in the title above.
and if I do a query like 
     "fieldName:val_IN_2000*"
I don't get an exception but I get 0 matching results.
Am I doing something wrong?

FYI... I am using OrderPreservingPartitioner in Cassandra.

**Comment by tjake** [comment]
Not able to reproduce your error,  in the first query.  Could it be you didn't refresh your index after I updated the internal format a week or so ago? try a fresh index.  

As for your second query, I don't think Lucene allows this.  You can enable something like this with  qp.setAllowLeadingWildcard( true );

Then "fieldname:_IN_2000_" will work but this is REALLY expensive, unless you have relatively few fieldname values.  

more info: http://wiki.apache.org/lucene-java/LuceneFAQ#What_wildcard_search_support_is_available_from_Lucene.3F
