### ISSUE TITLE
Delimiter used  for multi valued fields, please make it configurable

### ISSUE THREAD

**Issue by sdonelow** [tjake/Solandra#22]
Hello, I see that you fixed Issue 7, by changing  how multi valued fields work so that they get stored now by concatenating them with a space. Can you please make this delimiter configurable?  Our data has spaces in it, so it is impossible to tell where one record ends and the next one begins.

the other option would be to return the xml as elements instead of the <arr> type which just concats everything together.  I don't know if that is possible or not.

**Comment by tjake** [comment]
Hmm, let me think of a way to do this better. so the fields are returned as multiple fields in the document

**Comment by tjake** [comment]
This is now fixed, Document.getFields("fieldname") will now return you back multiple fields.
