### ISSUE TITLE
upgrade to lucene 3.0 perhaps

### ISSUE THREAD

**Issue by ceocoder** [tjake/Solandra#3]
I'm not sure if upgrading to lucene 3.0 will benifit or not, but if you are interested may be I can help out

**Comment by tjake** [comment]
I've tried it but stopped when all the tests broke :) I'll want todo this at some point, preferably when there is a real reason.  I'd happily accept a patch if you are willing to work on it. thx.

**Comment by kumm** [comment]
Hi!
I have a patch for Lucene 3.0.1. The unit test is working, and bookmarksdemo too.
Where (how) can i send it? I'm new at github...

**Comment by tjake** [comment]
thank you kumm, committed!
