### ISSUE TITLE
duplicate term key additions

### ISSUE THREAD

**Issue by cc2010** [tjake/Solandra#32]
IndexWriter
public void addDocument(Document doc, Analyzer analyzer) {
              ...
              // Indexed field
line 97:
              if (field.isIndexed()) {
               ...
              }
              //Untokenized fields go in without a termPosition
line 220:
             if (field.isIndexed() && !field.isTokenized()) {

If the field is indexed but not analyzed, then the term key will be added twice. It looks to me line 97 should be changed to 
             if (field.isIndexed() && field.isTokenized()) {

Please verify.

Thanks,
Chad

**Comment by tjake** [comment]
Are you saying you are seeing more than one being added?

I don't think this is the case.  If the field isn't tokenized then the there will be no tokens added, the second condition handles this (the case when its not tokenized).

Thanks, and let me know

**Comment by cc2010** [comment]
I did see duplicate values for NOT_ANALYZED field:
on line 102, the the tokens will be assigned the value of the untokenized field: 
    if (tokens == null) {
      tokens = analyzer.tokenStream(field.name(), new StringReader(field.stringValue()));
    }
