### ISSUE TITLE
Only 100 fields returned in query

### ISSUE THREAD

**Issue by sdonelow** [tjake/Solandra#35]
I am implementing some military data formats as solr schemas.  The GMTI format has over 200 fields.  Many of these fields are multivalued.   I created the schema file and put data in the database, no problem.  I can query on any of the fields, and I will get a hit if the query condition matches the data.

The document that is returned is truncating to 100 fields. I have tried calling setFaceLimit and setRows to a number much higher than 100, but that doesn't help.

Is there some parameter I have to set to retrievve more than 100 fields?  I know the fields are  in the document that was saved because I can search on them.

Help!

**Comment by sdonelow** [comment]
After researching this it seems that the problem is being caused in the class IndexReader, in the method document, at this line:
if (fieldNames == null || fieldNames.size() == 0) {
            // get all columns ( except this skips meta info )
            slicePredicate.setSlice_range(new SliceRange(new byte[] {}, CassandraUtils.finalToken.getBytes("UTF-8"), false, 100));
        } else {

```
        slicePredicate.setColumn_names(fieldNames);
    }
```

I'm not using a field selector so fieldNames is null when the above code is reached.

**Comment by sdonelow** [comment]
Yep, that was the problem.  I changed 100 to 1000 and recompiled and no more truncation of the fields.

**Comment by tjake** [comment]
Cool thanks. I'll make this configurable.

**Comment by sdonelow** [comment]
Set it to 1 billion so we don't have to futz with it.  LOL
