### ISSUE TITLE
tjake, please help me 

### ISSUE THREAD

**Issue by lixinchinaren** [tjake/Solandra#36]
hello, tjake,
  I am using the Lucandra, but I find that, when i search some data through BooleanQuery, i
can not get all data that satisfied the BooleanQuery, it always lose one. please tell me why?

**Comment by lixinchinaren** [comment]
my code for  input

...
Document doc = new Document();
String entryID = "id1";
String floorNum = "1";
doc.add(new Field(ENTRYNAME , entryID , Field.Store.YES , Field.Index.NOT_ANALYZED));
doc.add(new Field(FLOORNUM , floorNum , Field.Store.NO , Field.Index.NOT_ANALYZED));
indexWriter.addDocument(doc, analyzer);

**Comment by lixinchinaren** [comment]
my code for output
...
BooleanQuery booleanQuery = new BooleanQuery(false);
TermQuery termQ = new TermQuery(new Term(floorNum, "1"));
booleanQuery.add(termQ, Occur.MUST);
TopDocs docs = indexSearcher.search(termQ)
...

**Comment by lixinchinaren** [comment]
ignore

**Comment by tjake** [comment]
ignored
