### ISSUE TITLE
Sort doesn't work correctly in multi-thread.

### ISSUE THREAD

**Issue by mayah** [tjake/Solandra#37]
Hi, tjake

I met an issue that sort does not work correctly when I uses lucandra in multi-thread.

The main reason is that IndexReader uses ThreadLocal.

The Lucene caches a field in sorting. It uses the instance of IndexReader to get caches like the following: (copied form FieldCacheImpl)

 // inherit javadocs
 public int[] getInts(IndexReader reader, String field, IntParser parser)
     throws IOException {
    return (int[]) caches.get(Integer.TYPE).get(reader, new Entry(field, parser));
 }

Since I share the instance of IndexReader in several threads, this code returns the same field cache. However, the data of IndexReader differs in threads. So the Lucene may use unintended cache, which is created in another thread. This causes incorrect sorting.

The supportive care of this bug is not to share IndexReader in several threads. However, the Lucene says IndexReader is thread-safe, so I think the IndexReader of lucandra should be fixed.

**Comment by tjake** [comment]
Ah. I think this can be fixes by overriding indexreader.getfieldcachekey()
So each thread returns a diff key.

**Comment by mayah** [comment]
Hi, tjake.

I overrode IndexReader#getFieldCacheKey() so that each thread returns a different key, then it worked! I hope this issue is fixed in your master branch.

Thank you.

**Comment by amcjen** [comment]
Hey there-

Has this fix already been added to the master branch?  If not, mayah, maybe you could fork it and add the patch.  That'd let others get the fix, and let tjake merge it back in when he's ready/has a moment.

Thx!

**Comment by tjake** [comment]
fixed, thanks for the reminder!

**Comment by amcjen** [comment]
Super, thanks!  Just saw it on my pull.  :)
