### ISSUE TITLE
error on ./run-demo search

### ISSUE THREAD

**Issue by ceocoder** [tjake/Solandra#4]
Hi,

I setup lucandra and cassandra 0.6, and was able to index successfully, but searching for linux throws this error

z3r0c001@legolas:~/workspace/Libraries/Lucandra$ ./run_demo.sh -search title:linux
InvalidRequestException(why:start key's md5 sorts after end key's md5.  this is not allowed; you probably should not specify end key at all, under RandomPartitioner)

but searching for amazon returns normal results,

z3r0c001@legolas:~/workspace/Libraries/Lucandra$ ./run_demo.sh -search title:amazon
15:53:16,707 DEBUG LucandraTermEnum:199 - Found 2 keys in range:bookmarksÿÿtitleÿÿamazon to bookmarksÿÿtitlf in 39ms
15:53:16,710 DEBUG LucandraTermEnum:213 - titleÿÿamazon has 2
15:53:16,711 DEBUG LucandraTermEnum:213 - tagsÿÿachieving has 1
15:53:16,712 DEBUG LucandraTermEnum:248 - loadTerms: bookmarksÿÿtitleÿÿamazon(3) took 45ms
15:53:16,713  INFO IndexReader:135 - docFreq() took: 47ms
15:53:16,716 DEBUG LucandraTermEnum:154 - Found bookmarksÿÿtitleÿÿamazon in cache
Search matched: 2 item(s)
15:53:16,744 DEBUG IndexReader:193 - Document read took: 26ms
1. Setting up an Amazon EC2 server with Fedora Core 5 at Notes from a messy desk
    http://woss.name/2006/09/19/setting-up-an-amazon-ec2-server-with-fedora-core-5/
15:53:16,749 DEBUG IndexReader:193 - Document read took: 5ms
2. Amazon Web Services Developer Connection : HOWTO Building a self-bundling Debian ...
    http://developer.amazonwebservices.com/connect/thread.jspa?threadID=17046

pls let me know if I can help. 
thanks
z3r0

**Comment by tjake** [comment]
Looks like you are using the RandomPartitioner instead of the OrderPreservingPartitioner. This is required in the cassandras storage-conf.xml

**Comment by ceocoder** [comment]
that fixed it. thx
