### ISSUE TITLE
Caching breaks sort order on second and consecutive queries.

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#45]
The test that demonstrates this problem is an updated NumericRangeQuery.  You can find the test here.

https://github.com/tnine/Lucandra/blob/0.7/test/lucandra/NumericRangeTests.java

I have your latest code as of today, the testDocumentOrderingSearchTwice is the failing test.

**Comment by tjake** [comment]
properly fixed. https://github.com/tjake/Lucandra/commit/ed9ce5199f691f974a5becbda6454679bd1c177e
