### ISSUE TITLE
Problem with accents

### ISSUE THREAD

**Issue by levmatta** [tjake/Solandra#46]
I am developing for the pt_BR locale (lots of ã,õ,ç,á,...).
Searching words with these diacritic marks is Not working!!

With plain lucene I was using the following analyzer without problems:

> StandardAnalyzer defaultAnalyzer = new StandardAnalyzer(Version.LUCENE_30) {
>   @Override
>   public TokenStream tokenStream(String fieldName, Reader reader) {
>     return new ASCIIFoldingFilter(super.tokenStream(fieldName,reader));
>   }
> };
> 
> PerFieldAnalyzerWrapper analyser = new PerFieldAnalyzerWrapper(defaultAnalyzer);
> analyser.addAnalyzer(TAGS.getFieldName(), new CommaAnalyzer());
> analyser.addAnalyzer(StandardFieldEnum.PARENTS.getFieldName(),new CommaAnalyzer());
> 
> return analyser;

Please ignore the PerFiledAnalyzer, it is there just to be completly honest :).

Any Ideas?
Thanks.

**Comment by levmatta** [comment]
Please Some help.

**Comment by tjake** [comment]
Would you be able to supply a test so I can look into reproducing this? thanks!

**Comment by levmatta** [comment]
Yes, but It will take a while.
Thanks.

**Comment by tjake** [comment]
Is pt_BR locale considered UTF-8?  at this point all terms are stored as UTF-8.

**Comment by levmatta** [comment]
I am using UTF-8, but Latin extended does suffice.

**Comment by levmatta** [comment]
I am sorry but this is not a Lucandra problem. Lucene is to blame here.
The problem is that when Lucene sees a Wildcard it goes crazy with fear and does NOT
user my Analyzer. So ASCIIFoldingFilter is not being use.

**Comment by tjake** [comment]
Thanks, good to know
