### ISSUE TITLE
Sort results fails

### ISSUE THREAD

**Issue by mircouleur** [tjake/Solandra#5]
Hello, it's impossible to sort results with a huge database (many millions of entries).
Exception in thread "main" java.lang.IllegalStateException: numDocs reached.
And I don't really understand the use of "numDocs" in the IndexReader...
Thanx for your help

**Comment by tjake** [comment]
This number is a hardcoded limit currently (1000000) you can up it if you wish. Though pulling millions of columns from Cassandra to sort is going to be very expensive. 

I'm working on a better way to handle sorts (within Cassandra and not lucene)

Jake
