### ISSUE TITLE
bug in CassandraUtils.java, line 191

### ISSUE THREAD

**Issue by iron9light** [tjake/Solandra#6]
---            intArray[idx] = (b[i] << 24) + ((b[i + 1] & 0xFF) << 16) + ((b[i + 2] & 0xFF) << 8) + (b[i + 3] & 0xFF);
+++            intArray[idx++] = (b[i] << 24) + ((b[i + 1] & 0xFF) << 16) + ((b[i + 2] & 0xFF) << 8) + (b[i + 3] & 0xFF);

**Comment by tjake** [comment]
nice find! thanks, this affected exact searches with more than 1 of the same term 
"foo foo".  Added a test case as well, thx!
