### ISSUE TITLE
Comitting on solr client with .commit(true, true) does not actually wait for mutation to occur before returning

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#60]
Hi Jake,
  This is difficult to reproduce in a test, but can easily be demonstrated with a debugger.  This is how I can detected the issue.
1. Insert a breakpoint at org.apache.solr.handler.RequestHandlerUtils line 107 :processor.processCommit( cmd );
2. Insert a breakpoint in  lucandra.IndexWriter line 496:   CassandraUtils.robustInsert(CassandraUtils.consistency, rows.toArray(new RowMutation[] {}));
3. Insert any document with the following client code
   
      CommonsHttpSolrServer server = getClient(indexName.getIndex());
       server.add(docs);
       server.commit(true, true);
4. Step over the breakpoint in RequestHandlerUtils without continuing the breakpoint in IndexWriter.
5. The request that is processed in RequestHandlerUtils will return true, however the Thread processing the mutation has not actually completed its write yet.

I'm working on figuring out a way to synchronize this, but it doesn't seem like a trivial fix given the producer/consumer model of the writes.  This is a showstopper for us.  We have to be 100% certain our index write was successful before we continue processing.  While asynchronous writes will give us much better throughput, it will not give us the consistency required for our use case.

**Comment by tnine** [comment]
Scratch that.  Just tried to reproduce this error and couldn't.  Strangely I was seeing this issue when I was also seeing the NPE error.

**Comment by tjake** [comment]
Yeah if you look at SolandraIndexWriter.commit() it explicitly flushes the queued mutations.

Are you running with RF>1?

**Comment by tnine** [comment]
No yet, but I will be.  I changed the code to take a replication factor from the System properties, though a configuration file would be ideal.  

https://github.com/tnine/Lucandra/commit/c7d92719843abf3075311dac4faaf37c4fd7acaf

This works, but it's a bit of a fast hack to get a working dev environment working while a proper configuration is created.
