### ISSUE TITLE
High CPU usage with solandra.cache.invalidation.check.interval = 0

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#64]
Hi Jake,
  Today I noticed some issues with setting cachetime equal to 0.  If I have cache time set to the default of 1000 or greater, then start Cassandra, after compaction the CPU usages is periodically between 10 to 20% on a dual core system.  If I set the time to 0, it continues to use 100% after all compaction operations are complete.  This appears to be related to the timer loop executing with every iteration, essentially creating a busy wait.  Is it possible to restructure this to remove the cache and this loop if the time is == 0?

**Comment by tjake** [comment]
Yeah, I noticed this too. I'll fix it.

**Comment by tjake** [comment]
The best I can do here is ignore this completely and just re-search every-time.  I was hoping to think of a way to avoid doing this since you don't want to do this when there is no writes happening...

**Comment by tjake** [comment]
Hi Todd, I added a fix for this, basically cachetime=0 bypasses the async queue
