### ISSUE TITLE
only one value gets stored on multivalued fields

### ISSUE THREAD

**Issue by efalcao** [tjake/Solandra#7]
Please forgive me if I'm totally wrong, but I'm not much of a Solr or Java guy. I ran through your getting started and it seems as though multivalued fields like category only store one value even though the document had many. It seems as though it still matches on all of the values, but only stores one. Is this desired? I guess I would prefer to have all the values there so i didn't have to go hit another source...

Thanks for your hard work!

**Comment by eurospy** [comment]
I think you're right, I've faced the same issue. However indexing on multivalued fields are working fine

**Comment by sdonelow** [comment]
I am finding the same issue.  Indexing and search on multivalued fields works but storing the values does not work.  As a temporary work around I am going to add a field which has all the values concatenated together separated by a delimiter.

**Comment by tjake** [comment]
Ok, finally fixed this. fields with same name are not concatenated together and separated by a space.
