### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by JimKerwood** [tjake/Solandra#73]
I have setup solandra in a currently running cluster.  I have the latest solandra running on a 6 box cassandra 0.7.4 cluster.  I used the reuters-demo and the upload worked fine.  Well it did error after - reut2-016.sgm(999) but data was in cassandra and that is what I cared about.

When I query I get:
Problem accessing /solandra/reuters/select. Reason: 

```
org.apache.solr.client.solrj.SolrServerException: java.net.ConnectException: Connection refused
```

org.apache.solr.common.SolrException: org.apache.solr.client.solrj.SolrServerException: java.net.ConnectException: Connection refused
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:282)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
...

I am running all 6 on 8085 not the default 8983.
Interestingly if I query with &shards=server:8085/solandra/reuters
I get no error but I also get no resutls.

Maybe I'll try setting all boxes to the default port and try again...

**Comment by tjake** [comment]
Ah I think I have 8983 hardcoded. I need to fix that. Thanks
