### ISSUE TITLE
Faceting not working correctly

### ISSUE THREAD

**Issue by davidstrauss** [tjake/Solandra#78]
I've installed Drupal's Solr schema, indexed some sample content, and attempted use of faceting. Adding a facet to an existing text query seems to have no effect. Running a query with only a facet seems to cause a 500 error. Is this a known issue?

**Comment by tjake** [comment]
Do you have any details on the underlying facet query?  Some types of faceting don't work with distributed search

**Comment by davidstrauss** [comment]
It's a simple equality filter on a uid field.

**Comment by tjake** [comment]
Can you provide me with a way to reproduce this?

**Comment by davidstrauss** [comment]
I'll try to develop a simple set of steps for reproduction. Is 64-bit Ubuntu 10.04 okay?

**Comment by davidstrauss** [comment]
I cannot reproduce this issue on the latest HEAD.
