### ISSUE TITLE
Search function does not fully support (?q=)

### ISSUE THREAD

**Issue by Gasol** [tjake/Solandra#80]
index some text like "first second third"

curl 'http://localhost:8983/solandra/reuters/analysis/field?analysis.fieldtype=text&q=first second third&analysis.fieldvalue=first&wt=json&indent=true&analysis.showmatch=true'

i got "first" match.

but i can not query like below:

curl 'http://localhost:8983/solandra/reuters/select?q=first second' // numFound=0, expect 1
but
curl 'http://localhost:8983/solandra/reuters/select?q=first' // numFound=1

**Comment by davidstrauss** [comment]
@Gasol Does this problem still occur for you when you escape the space with "%20" or "+"? I can't reproduce this issue using normal URL escaping.

**Comment by Gasol** [comment]
i'll give it a try...
