### ISSUE TITLE
Terms Query Not Working

### ISSUE THREAD

**Issue by jschappet** [tjake/Solandra#85]
Should this query work in Solandra?

http://localhost:8983/solandra/reuters/terms?terms.fl=combo&terms.regex=Coffee.*&terms.regex.flag=case_insensitive

I saw the comment in solrconfig.xml, about terms, but I am not sure if this is a distributed search.

Right now I am getting empty results:

<code>
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;response&gt;
&lt;lst name="responseHeader"&gt;&lt;int name="status"&gt;0&lt;/int&gt;&lt;int name="QTime"&gt;1&lt;/int&gt;&lt;/lst&gt;&lt;lst name="terms"&gt;&lt;lst name="combo"/&gt;&lt;/lst&gt;
&lt;/response&gt;
</code>

**Comment by jschappet** [comment]
In the Cassandra Log:

 INFO [347500362@qtp-698491110-3] 2011-05-10 08:05:53,005 SolrCore.java (line 1370) [reuters] webapp=/solandra path=/terms params={terms.regex=Coffee.*&terms.regex.flag=case_insensitive&terms.fl=combo} status=0 QTime=170

**Comment by tjake** [comment]
I have't tried that search type is that new in 3.1?  In theory it should work.

Let me add a test case and see what's happening

**Comment by jschappet** [comment]
Jake,

Is there anything I might be able to try on my side to get this working?

--Jimmy

**Comment by tjake** [comment]
Hi Jimmy,

Working on a different issue atm. I will get to this soon after.

Thanks!

**Comment by tjake** [comment]
Hi Jimmy,

This requires a custom TermsComponent, I'll work on it this week.

**Comment by tjake** [comment]
Just committed. Please take a look.

**Comment by jschappet** [comment]
Search terms are working.  

Thanks for the updates Jake.
