### ISSUE TITLE
Facet counts inaccurate

### ISSUE THREAD

**Issue by davidstrauss** [tjake/Solandra#89]
The facet counts returned by Solandra appear to either approximate the results or use stale cached values. The results of filtering by the facet are still correct. The standard Solr server reports the exact count in all cases we've tried. Is this intentional? Is there an expected range or level of precision that should bound the facet counts from Solandra?

**Comment by tjake** [comment]
There are 2 things you can do:
1. Call commit when you are done writing documents and you want docs to be reflected in the readers.
2. In solandra.properties you can set the solandra.cache.invalidation.check.interval=0 to get "real-time" results.

**Comment by tjake** [comment]
This is fixed by https://github.com/tjake/Solandra/commit/89851030eacc27474b5f99e5cc8323c17894897f
