### ISSUE TITLE
deleteDocuments via Lucandra.IndexWriter

### ISSUE THREAD

**Issue by mevivs** [tjake/Solandra#97]
Hi Jake,
I am trying to get deleteDocuments via Term working. But somehow i can see it is not working for me. What i am trying is to insert a document and delete the same using indexName. Then retrieve the same using search via Lucandra.IndexReader. I am getting an error like 
{why: Unconfigured columnFamily: Authors). 

Authors is my columnFamily which i created earlier.

Any idea?

**Comment by tjake** [comment]
What are you doing to get that error?  Are you not using solr?  You can't use IndexWriter directly... you _must_ use the solr delete api

**Comment by mevivs** [comment]
It is working fine now. By mistake added a code snippet to delete col family.
